"use client";

import Card from "@/components/ui/Card";
import { ShieldCheck, AlertTriangle, Sparkles } from "lucide-react";

export default function AIVerdict() {
  return (
    <Card title="AI Verdict">
      <div className="space-y-5">

        <div className="flex items-center gap-3 rounded-xl bg-emerald-500/10 p-4">
          <ShieldCheck className="text-emerald-400" />
          <div>
            <p className="font-semibold text-white">
              Overall Risk
            </p>
            <p className="text-sm text-emerald-400">
              LOW
            </p>
          </div>
        </div>

        <div>
          <p className="mb-3 text-sm font-semibold text-white">
            AI Analysis
          </p>

          <ul className="space-y-3 text-sm text-zinc-400">
            <li>✓ Wallet shows healthy on-chain activity.</li>
            <li>✓ No known malicious contracts detected.</li>
            <li>✓ Active across multiple supported networks.</li>
            <li>✓ Consistent transaction history.</li>
          </ul>
        </div>

        <div className="rounded-xl border border-yellow-500/20 bg-yellow-500/10 p-4">
          <div className="flex gap-3">
            <AlertTriangle
              size={20}
              className="mt-0.5 text-yellow-400"
            />

            <div>
              <p className="font-medium text-white">
                Recommendation
              </p>

              <p className="mt-1 text-sm text-zinc-400">
                Review old token approvals regularly to reduce attack surface.
              </p>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2 text-violet-400">
          <Sparkles size={18} />

          <span className="text-sm">
            Generated by Shadow AI
          </span>
        </div>

      </div>
    </Card>
  );
}